# Generated by Django 3.2.4 on 2021-06-15 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20210615_1508'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classrooms',
            new_name='Classroom',
        ),
        migrations.RenameModel(
            old_name='Groups',
            new_name='Group',
        ),
        migrations.RenameModel(
            old_name='Subjects',
            new_name='Subject',
        ),
        migrations.RenameModel(
            old_name='Teachers',
            new_name='Teacher',
        ),
    ]
