# Generated by Django 3.2.4 on 2021-06-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_auto_20210616_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
