# Generated by Django 3.2.4 on 2021-06-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_schedule_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='position',
            field=models.IntegerField(),
        ),
    ]
