# Generated by Django 3.2.4 on 2021-06-30 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_auto_20210630_2033'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subgroups',
            new_name='Subgroup',
        ),
    ]
