# Generated by Django 3.2.4 on 2021-06-30 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_rename_subgroups_subgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.schedulestatus'),
        ),
    ]
