# Generated by Django 3.2.4 on 2021-07-07 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0013_alter_schedule_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['building', 'floor', 'number'], 'verbose_name': 'Кабинет', 'verbose_name_plural': 'Кабинеты'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name'], 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписания'},
        ),
        migrations.AlterModelOptions(
            name='schedulestatus',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='subgroup',
            options={'ordering': ['number'], 'verbose_name': 'Подгруппа', 'verbose_name_plural': 'Подгруппы'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name'], 'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['surname', 'name', 'patronymic'], 'verbose_name': 'Преподаватель', 'verbose_name_plural': 'Преподаватели'},
        ),
        migrations.AlterModelOptions(
            name='week',
            options={'ordering': ['number'], 'verbose_name': 'Неделя', 'verbose_name_plural': 'Недели'},
        ),
        migrations.AlterModelOptions(
            name='weekday',
            options={'ordering': ['pk'], 'verbose_name': 'День недели', 'verbose_name_plural': 'Дни недели'},
        ),
    ]
