# Generated by Django 3.2.4 on 2021-08-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_auto_20210814_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='week',
            field=models.IntegerField(choices=[(0, 'Все недели'), (1, 'Первая неделя'), (2, 'Вторая неделя')], default=0),
        ),
    ]
