# Generated by Django 3.2.4 on 2021-08-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0017_delete_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='subgroup',
            field=models.IntegerField(choices=[(0, 'Вся группа'), (1, 'Первая подгруппа'), (2, 'Вторая подгруппа')], default=0),
        ),
    ]
