# Generated by Django 3.2.4 on 2021-08-14 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0019_alter_schedule_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScheduleStatus',
        ),
        migrations.DeleteModel(
            name='Subgroup',
        ),
    ]
