# Generated by Django 3.2.4 on 2021-08-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0020_auto_20210814_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.IntegerField(choices=[(0, 'Практика'), (1, 'Учеба'), (2, 'Экзамены')], default=0),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subgroup',
            field=models.IntegerField(choices=[(0, 'Вся группа'), (1, 'Первая подгруппа'), (2, 'Вторая подгруппа')], default=0, verbose_name='Подгруппа'),
        ),
    ]
