# Generated by Django 3.2.4 on 2021-08-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0021_auto_20210814_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.IntegerField(choices=[(0, 'Практика'), (1, 'Учеба'), (2, 'Экзамены')], default=1),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='weekday',
            field=models.CharField(choices=[('mon', 'Понедельник'), ('tue', 'Вторник'), ('wed', 'Среда'), ('thu', 'Четверг'), ('fri', 'Пятница'), ('sat', 'Суббота'), ('sun', 'Воскресенье')], max_length=3),
        ),
    ]
