# Generated by Django 3.2.4 on 2021-08-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0025_delete_weekday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='position',
            field=models.IntegerField(choices=[(1, 'Первая пара'), (2, 'Вторая пара'), (3, 'Третья пара'), (4, 'Четвертая пара'), (5, 'Пятая пара')]),
        ),
    ]
