# Generated by Django 3.2.4 on 2021-08-21 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0026_alter_schedule_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['group', 'weekday', 'position', 'week', 'subgroup'], 'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписания'},
        ),
        migrations.AlterField(
            model_name='classroom',
            name='building',
            field=models.IntegerField(verbose_name='Строение'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='floor',
            field=models.IntegerField(verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='number',
            field=models.IntegerField(verbose_name='Кабинет'),
        ),
        migrations.AlterField(
            model_name='group',
            name='curator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.teacher', verbose_name='Куратор'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.classroom', verbose_name='Кабинет'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='position',
            field=models.IntegerField(choices=[(1, 'Первая пара'), (2, 'Вторая пара'), (3, 'Третья пара'), (4, 'Четвертая пара'), (5, 'Пятая пара')], verbose_name='Пара'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.IntegerField(choices=[(1, 'Учеба'), (2, 'Практика'), (3, 'Экзамены')], default=1, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.teacher', verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='week',
            field=models.IntegerField(choices=[(0, 'Обе недели'), (1, 'Первая неделя'), (2, 'Вторая неделя')], default=0, verbose_name='Неделя'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='weekday',
            field=models.IntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.classroom', verbose_name='Кабинет'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='patronymic',
            field=models.CharField(max_length=50, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='surname',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.DeleteModel(
            name='Teacher_Subject',
        ),
    ]
