# Generated by Django 3.2.4 on 2021-08-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0027_auto_20210821_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.IntegerField(choices=[(0, 'Не активен'), (1, 'Учеба'), (2, 'Практика'), (3, 'Экзамены')], default=1, verbose_name='Состояние'),
        ),
    ]
