# Generated by Django 3.2.6 on 2021-08-27 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0035_remove_schedule_sublesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='cabinet',
            field=models.CharField(max_length=10, null=True, verbose_name='Кабинет'),
        ),
    ]
