# Generated by Django 3.2.6 on 2021-08-27 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0036_classroom_cabinet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['cabinet'], 'verbose_name': 'Кабинет', 'verbose_name_plural': 'Кабинеты'},
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='building',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='number',
        ),
    ]
